// demo/angular-router/app.component.ts
import { Component, inject, signal } from '@angular/core';
import { NavigationEnd, Router, RouterOutlet } from '@angular/router';
import { GLYPHNAV } from 'glyphnav/angular-router';
import type { AnimateScope, CommitTiming, GlyphEffect } from 'glyphnav/core';
import { GlyphnavLinkDirective } from './glyphnav-link.directive';
import {
  charsets,
  CONTROL_TOOLTIPS,
  currentUrl,
  DEFAULT_TOOLBAR,
  durationToSlider,
  loadToolbar,
  saveToolbar,
  sliderToDuration,
} from '../shared/content';
import { initCodeBlocks } from '../shared/code-blocks';
import { initTheme } from '../shared/theme';
import { initTooltips } from '../shared/tooltip';
import logoSrc from '../shared/logo.svg';

/** This page's own localStorage key — not shared with the other demos. */
const STORE_KEY = 'angular-router';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, GlyphnavLinkDirective],
  template: `
    <h1 data-fw="angular-router">
      <img class="glyph-mark" [src]="logo" alt="" />
      <a [href]="base" data-glyphnav="off">glyphnav</a>
      <span class="sep">/</span>
      <span class="crumb">angular-router</span>
    </h1>

    <p class="bar" [class.resolving]="resolving()">
      Watch the address bar. Current path: <span class="path">{{ path() }}</span>
    </p>

    <nav aria-label="demo pages">
      <a [href]="appBase" glyphnavLink="/" [class.active]="active() === '/'">Home</a>
      <a [href]="appBase + 'about'" glyphnavLink="/about" [class.active]="active() === '/about'"
        >About</a
      >
      <a [href]="appBase + 'docs'" glyphnavLink="/docs" [class.active]="active() === '/docs'"
        >Docs</a
      >
      <a [href]="appBase + 'blog'" glyphnavLink="/blog" [class.active]="active() === '/blog'"
        >Blog</a
      >
    </nav>

    <nav class="deep" aria-label="deep links">
      deep links:
      <a [href]="appBase + 'about?ref=deep&page=2'" glyphnavLink="/about?ref=deep&page=2">?query</a>
      <a [href]="appBase + 'docs#options'" glyphnavLink="/docs#options">#hash</a>
      <a [href]="appBase + 'about?q=glyph#results'" glyphnavLink="/about?q=glyph#results"
        >?query+#hash</a
      >
    </nav>

    <div class="controls">
      <label [attr.data-tip]="tips.charset"
        >charset
        <select [value]="charset()" (change)="onCharset($event)">
          <option value="url">url-safe</option>
          <option value="hex">hex</option>
          <option value="matrix">matrix</option>
          <option value="symbols">symbols</option>
        </select>
      </label>
      <label [attr.data-tip]="tips.speed"
        >speed
        <input
          type="range"
          min="20"
          max="1000"
          step="10"
          [value]="durationToSlider(duration())"
          [attr.aria-valuetext]="duration() + 'ms'"
          (input)="onSpeed($event)"
        />
        <span class="ms">{{ duration() }}ms</span>
      </label>
      <label [attr.data-tip]="tips.effect"
        >effect
        <select [value]="effect()" (change)="onEffect($event)">
          <option value="decode">decode</option>
          <option value="scramble">scramble</option>
        </select>
      </label>
      <label [attr.data-tip]="tips.commit"
        >commit
        <select [value]="commit()" (change)="onCommit($event)">
          <option value="before">navigate first</option>
          <option value="after">animate first</option>
        </select>
      </label>
      <label [attr.data-tip]="tips.scope"
        >scope
        <select [value]="scope()" (change)="onScope($event)">
          <option value="full">full</option>
          <option value="tail">tail</option>
        </select>
      </label>
      <label class="toggle" [attr.data-tip]="tips.backForward">
        <input type="checkbox" [checked]="backForward()" (change)="onBackForward($event)" />
        back/forward
      </label>
    </div>

    <router-outlet></router-outlet>

    <p class="foot">
      The <code>[glyphnavLink]</code> directive is copied from this demo into your app and calls the
      injected navigator. Compiled with Angular JIT inside the shared playground — the title link is
      a plain full-page load back to the picker.
    </p>
  `,
})
export class AppComponent {
  private readonly nav = inject(GLYPHNAV);

  // '/' in dev, '/glyphnav/' on the deployed project page. The glyphnavLink
  // directive routes base-aware on its own; these drive the visible hrefs.
  readonly base = import.meta.env.BASE_URL;
  readonly appBase = `${this.base}angular-router/`;
  // The shared glyphnav logo mark, shown before the wordmark in the breadcrumb.
  readonly logo = logoSrc;

  // Restore this page's toolbar (charset is the option key; resolved to a glyph
  // pool only when handing options to the controller). Not shared with other demos.
  private readonly saved = loadToolbar(STORE_KEY, DEFAULT_TOOLBAR);

  readonly path = signal(currentUrl());
  readonly resolving = signal(false);
  readonly active = signal('/');
  readonly tips = CONTROL_TOOLTIPS;

  readonly charset = signal(this.saved.charset);
  readonly duration = signal(this.saved.duration);
  readonly effect = signal<GlyphEffect>(this.saved.effect);
  readonly commit = signal<CommitTiming>(this.saved.commit);
  readonly scope = signal<AnimateScope>(this.saved.scope);
  readonly backForward = signal(this.saved.backForward);

  // Back/forward animation is opt-in; the checkbox attaches/detaches the
  // popstate listener (the cleanup returned by enableHistoryAnimation).
  private stopPopState: (() => void) | null = null;

  // Exposed for the template's inverted speed slider.
  readonly durationToSlider = durationToSlider;

  constructor() {
    this.apply();
    // Wire the theme switcher + styled control tooltips + code-block helpers once.
    initTheme();
    initTooltips();
    initCodeBlocks();
    if (this.backForward()) {
      this.stopPopState = this.nav.controller.enableHistoryAnimation();
    }
    inject(Router).events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        // Keep the full URL (incl. query/hash) so a deep link like
        // /about?ref=deep never matches a plain tab target ('/about') below.
        this.active.set(event.urlAfterRedirects);
      }
    });
  }

  private apply(): void {
    this.nav.controller.update({
      charset: charsets[this.charset()],
      duration: this.duration(),
      effect: this.effect(),
      commit: this.commit(),
      scope: this.scope(),
      hooks: {
        onFrame: (f) => {
          this.path.set(f.path);
          this.resolving.set(f.phase === 'resolve');
        },
        onComplete: () => {
          this.resolving.set(false);
          this.path.set(currentUrl());
        },
      },
    });
    this.persist();
  }

  private persist(): void {
    saveToolbar(STORE_KEY, {
      charset: this.charset(),
      duration: this.duration(),
      effect: this.effect(),
      commit: this.commit(),
      scope: this.scope(),
      backForward: this.backForward(),
    });
  }

  onCharset(event: Event): void {
    this.charset.set((event.target as HTMLSelectElement).value);
    this.apply();
  }

  onSpeed(event: Event): void {
    // Slider is inverted: full right = 20 ms (fastest whole animation).
    this.duration.set(sliderToDuration(Number((event.target as HTMLInputElement).value)));
    this.apply();
  }

  onEffect(event: Event): void {
    this.effect.set((event.target as HTMLSelectElement).value as GlyphEffect);
    this.apply();
  }

  onCommit(event: Event): void {
    this.commit.set((event.target as HTMLSelectElement).value as CommitTiming);
    this.apply();
  }

  onScope(event: Event): void {
    this.scope.set((event.target as HTMLSelectElement).value as AnimateScope);
    this.apply();
  }

  onBackForward(event: Event): void {
    const on = (event.target as HTMLInputElement).checked;
    this.backForward.set(on);
    if (on && !this.stopPopState) {
      this.stopPopState = this.nav.controller.enableHistoryAnimation();
    } else if (!on && this.stopPopState) {
      this.stopPopState();
      this.stopPopState = null;
    }
    this.persist();
  }
}

// demo/nuxt/app.vue
<script setup lang="ts">
import type { AnimateScope, CommitTiming, GlyphEffect } from 'glyphnav/core';
import {
  charsets,
  CONTROL_TOOLTIPS,
  currentUrl,
  DEFAULT_TOOLBAR,
  durationToSlider,
  initCodeBlocks,
  initTheme,
  initTooltips,
  loadToolbar,
  saveToolbar,
  sliderToDuration,
  THEME_INIT_SCRIPT,
} from '@glyphnav-demo/shared';
import logo from '@glyphnav-demo/shared/logo.svg';

// SEO / social + AI link previews. Absolute URLs so the tags stay correct in the
// statically generated output served from the GitHub Pages project subpath.
useHead({
  link: [
    { rel: 'canonical', href: 'https://z1m1n.github.io/glyphnav/nuxt/' },
    { rel: 'icon', type: 'image/svg+xml', href: 'https://z1m1n.github.io/glyphnav/favicon.svg' },
  ],
  meta: [{ name: 'theme-color', content: '#ffffff' }],
  // Apply the saved/OS theme before first paint (no flash). `tagPriority` puts it
  // ahead of other head tags so it runs as early as possible.
  script: [{ innerHTML: THEME_INIT_SCRIPT, tagPosition: 'head', tagPriority: 'critical' }],
});
useSeoMeta({
  title: 'glyphnav — nuxt',
  description:
    'glyphnav for Nuxt: a client plugin wraps router.push / navigateTo so every NuxtLink animates the destination URL in the address bar. Live, interactive demo.',
  ogType: 'website',
  ogSiteName: 'glyphnav',
  ogTitle: 'glyphnav — Nuxt demo',
  ogDescription:
    'A client plugin wraps router.push / navigateTo so every NuxtLink animates the destination URL in the address bar.',
  ogUrl: 'https://z1m1n.github.io/glyphnav/nuxt/',
  ogImage: 'https://z1m1n.github.io/glyphnav/og.png',
  twitterCard: 'summary_large_image',
  twitterImage: 'https://z1m1n.github.io/glyphnav/og.png',
});

// The picker lives one level up from this app's base (`/glyphnav/nuxt/` →
// `/glyphnav/`). A plain anchor does the full reload back to it.
const config = useRuntimeConfig();
const baseURL = config.app.baseURL;
const rootHref = baseURL.replace(/nuxt\/$/, '') || '/';
const stack = config.public.stack;

/** This page's own localStorage key — not shared with the other demos. */
const STORE_KEY = 'nuxt';
const tips = CONTROL_TOOLTIPS;

// A tab is active only on an exact match (full path incl. query/hash), instead
// of <NuxtLink>'s built-in active class which ignores the query — so a deep link
// like /about?ref=deep never lights up the plain "About" tab.
const route = useRoute();
const isActive = (to: string): boolean => route.fullPath === to;

// Refs start at the defaults so the prerendered markup is stable; the saved
// toolbar is restored on the client in onMounted (after hydration).
const path = ref('/');
const resolving = ref(false);
const charset = ref('url');
const duration = ref(250);
const effect = ref<GlyphEffect>('decode');
const commit = ref<CommitTiming>('before');
const scope = ref<AnimateScope>('full');
const backForward = ref(true);

// Back/forward animation is opt-in; the checkbox attaches/detaches the popstate
// listener. The instance only exists client-side, so this runs from onMounted.
let stopPopState: (() => void) | null = null;
function applyBackForward(): void {
  const instance = useNuxtApp().$glyphnav;
  if (!instance) return;
  if (backForward.value && !stopPopState) {
    stopPopState = instance.controller.enableHistoryAnimation();
  } else if (!backForward.value && stopPopState) {
    stopPopState();
    stopPopState = null;
  }
}

function persist(): void {
  saveToolbar(STORE_KEY, {
    charset: charset.value,
    duration: duration.value,
    effect: effect.value,
    commit: commit.value,
    scope: scope.value,
    backForward: backForward.value,
  });
}

function apply(): void {
  const instance = useNuxtApp().$glyphnav;
  if (!instance) return; // absent during SSR/prerender
  instance.controller.update({
    charset: charsets[charset.value],
    duration: duration.value,
    effect: effect.value,
    commit: commit.value,
    scope: scope.value,
    hooks: {
      onFrame: (f) => {
        path.value = f.path;
        resolving.value = f.phase === 'resolve';
      },
      onComplete: () => {
        resolving.value = false;
        path.value = currentUrl();
      },
    },
  });
  persist();
}

onMounted(() => {
  const saved = loadToolbar(STORE_KEY, DEFAULT_TOOLBAR);
  charset.value = saved.charset;
  duration.value = saved.duration;
  effect.value = saved.effect;
  commit.value = saved.commit;
  scope.value = saved.scope;
  backForward.value = saved.backForward;
  path.value = currentUrl();
  apply();
  applyBackForward();
  // Wire the theme switcher + styled control tooltips + code-block helpers.
  initTheme();
  initTooltips();
  initCodeBlocks();
});
watch([charset, duration, effect, commit, scope], apply);
watch(backForward, () => {
  applyBackForward();
  persist();
});
</script>

<template>
  <div class="app-shell">
    <h1 data-fw="nuxt">
      <img class="glyph-mark" :src="logo" alt="" />
      <a :href="rootHref">glyphnav</a>
      <span class="sep">/</span>
      <span class="crumb">nuxt</span>
    </h1>

    <p :class="resolving ? 'bar resolving' : 'bar'">
      Watch the address bar. Current path: <span class="path">{{ path }}</span>
    </p>

    <nav aria-label="demo pages">
      <NuxtLink to="/" :class="{ active: isActive('/') }">Home</NuxtLink>
      <NuxtLink to="/about" :class="{ active: isActive('/about') }">About</NuxtLink>
      <NuxtLink to="/docs" :class="{ active: isActive('/docs') }">Docs</NuxtLink>
      <NuxtLink to="/features" :class="{ active: isActive('/features') }">Features</NuxtLink>
    </nav>

    <nav class="deep" aria-label="deep links">
      deep links:
      <NuxtLink to="/about?ref=deep&page=2">?query</NuxtLink>
      <NuxtLink to="/docs#options">#hash</NuxtLink>
      <NuxtLink to="/about?q=glyph#results">?query+#hash</NuxtLink>
    </nav>

    <div class="controls">
      <label :data-tip="tips.charset">
        charset
        <select v-model="charset">
          <option value="url">url-safe</option>
          <option value="hex">hex</option>
          <option value="matrix">matrix</option>
          <option value="symbols">symbols</option>
        </select>
      </label>
      <label :data-tip="tips.speed">
        speed
        <input
          type="range"
          :min="20"
          :max="1000"
          :step="10"
          :value="durationToSlider(duration)"
          :aria-valuetext="`${duration}ms`"
          @input="duration = sliderToDuration(Number(($event.target as HTMLInputElement).value))"
        />
        <span class="ms">{{ duration }}ms</span>
      </label>
      <label :data-tip="tips.effect">
        effect
        <select v-model="effect">
          <option value="decode">decode</option>
          <option value="scramble">scramble</option>
        </select>
      </label>
      <label :data-tip="tips.commit">
        commit
        <select v-model="commit">
          <option value="before">navigate first</option>
          <option value="after">animate first</option>
        </select>
      </label>
      <label :data-tip="tips.scope">
        scope
        <select v-model="scope">
          <option value="full">full</option>
          <option value="tail">tail</option>
        </select>
      </label>
      <label class="toggle" :data-tip="tips.backForward">
        <input v-model="backForward" type="checkbox" />
        back/forward
      </label>
    </div>

    <NuxtPage />

    <p class="foot">
      Served under the <code>/nuxt</code> base via Nuxt's <code>app.baseURL</code>; the Nuxt plugin
      wraps <code>router.push</code> so every <code>&lt;NuxtLink&gt;</code> and
      <code>navigateTo()</code> animates. The title link is a plain anchor (full page load back to
      the picker).
    </p>

    <footer class="site-footer">
      <a href="https://github.com/z1m1n/glyphnav" target="_blank" rel="noopener">GitHub</a>
      <a href="https://www.npmjs.com/package/glyphnav" target="_blank" rel="noopener">NPM</a>
      <!-- The changelog lives in the combined demo site, one level up from this
           app's base — a plain anchor so it does a full navigation. -->
      <a :href="`${rootHref}changelog/`">Changelog</a>
      <span class="stack">{{ stack }}</span>
    </footer>
  </div>
</template>
