// demo/sveltekit/src/routes/docs/+page.svelte
<script lang="ts">
  import { DOCS_INSTALL, highlight } from '@glyphnav-demo/shared';

  const DOCS_SETUP = `<!-- src/routes/+layout.svelte -->
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { attachGlyphnav } from 'glyphnav/sveltekit';

  // Every <a> click and goto() now animates first.
  onMount(() => attachGlyphnav(goto, { duration: 250, commit: 'before' }).detach);
${'<'}/script>`;

  const DOCS_VARIANTS = `// Leave clicks to SvelteKit, animate only explicit calls:
const { navigate, link } = attachGlyphnav(goto, { intercept: 'none' });
await navigate('/dashboard', { replace: true });

// …or opt a single link in with the action:
//   <a href="/about" use:link>About</a>`;

  const DOCS_OPTIONS = `attachGlyphnav(goto, {
  duration: 250,         // total animation time (ms), spread over all frames
  effect: 'scramble',    // 'decode' grows + resolves; 'scramble' bursts, then locks randomly
  commit: 'before',      // navigate instantly, animate on top ('after' = classic order)
  intercept: 'links',    // capture-phase <a> interception ('none' = explicit-only)
  scope: 'tail',         // animate only the part that differs from the current path
  animatePopState: true, // also animate browser back/forward (opt-in)
});`;
</script>

<div class="view docs">
  <article>
    <header class="lead">
      <h2>Docs</h2>
      Install the package — SvelteKit stays a peer dependency:
    </header>
    <figure>
      <pre><code>{@html highlight(DOCS_INSTALL)}</code></pre>
    </figure>
    <figure>
      <figcaption>
        Attach once in the root layout; every <code>&lt;a&gt;</code> then animates:
      </figcaption>
      <pre><code>{@html highlight(DOCS_SETUP)}</code></pre>
    </figure>
    <figure>
      <figcaption>Or leave clicks to SvelteKit and animate explicit calls only:</figcaption>
      <pre><code>{@html highlight(DOCS_VARIANTS)}</code></pre>
    </figure>
    <figure>
      <figcaption id="options">Every entry point accepts the same options object:</figcaption>
      <pre><code>{@html highlight(DOCS_OPTIONS)}</code></pre>
    </figure>
    <aside class="note">
      <strong>Caveat:</strong> every frame writes via <code>history.replaceState</code>,
      so back/forward stays untouched — but the browser's own URL history/autocomplete
      (and any extension listening for <code>webNavigation.onHistoryStateUpdated</code>)
      can still log each frame as a visit. There's no API to opt a <code>replaceState</code>
      call out of that; keep <code>duration</code> short, <code>maxFrames</code> low, or use
      <code>scope: 'tail'</code> to cut the frame count.
    </aside>
  </article>
</div>

// demo/next/app/docs/page.tsx
import type { ReactNode } from 'react';
import { DOCS_INSTALL, highlight } from '@glyphnav-demo/shared';

const DOCS_SETUP = `// app/providers.tsx  ('use client')
import { GlyphnavProvider, GlyphnavLink, useGlyphnavNavigate } from 'glyphnav/next';

<GlyphnavProvider duration={250} commit="before" routerMode="app">
  <GlyphnavLink href="/about?tab=2#top">About</GlyphnavLink>
</GlyphnavProvider>;

// imperative, mirrors useRouter().push:
const navigate = useGlyphnavNavigate();
await navigate('/dashboard');`;

const DOCS_VARIANTS = `// Pages Router? Flip one option — the adapter then drives
// next/compat/router instead of next/navigation:
<GlyphnavProvider routerMode="pages">…</GlyphnavProvider>

// Served under a base path? Pass it so commit: 'after' stays accurate:
<GlyphnavProvider basePath="/glyphnav/next">…</GlyphnavProvider>`;

const DOCS_OPTIONS = `<GlyphnavProvider
  duration={250}        // total animation time (ms), spread over all frames
  effect="scramble"     // 'decode' grows + resolves; 'scramble' bursts, then locks randomly
  commit="before"       // navigate instantly, animate on top ('after' = classic order)
  routerMode="app"      // 'app' (next/navigation) or 'pages' (next/compat/router)
  scope="tail"          // animate only the part that differs from the current path
  animatePopState       // also animate browser back/forward (opt-in)
>`;

/** A code listing as a captioned <figure>. */
function Figure({
  code,
  caption,
  captionId,
}: {
  code: string;
  caption?: ReactNode;
  captionId?: string;
}) {
  return (
    <figure>
      {caption ? <figcaption id={captionId}>{caption}</figcaption> : null}
      <pre>
        <code dangerouslySetInnerHTML={{ __html: highlight(code) }} />
      </pre>
    </figure>
  );
}

export default function Docs() {
  return (
    <div className="view docs">
      <article>
        <header className="lead">
          <h2>Docs</h2>
          Install the package — Next.js stays a peer dependency:
        </header>
        <Figure code={DOCS_INSTALL} />
        <Figure
          caption={
            <>
              <code>GlyphnavLink</code> is a drop-in for <code>next/link</code>; nothing is patched
              globally:
            </>
          }
          code={DOCS_SETUP}
        />
        <Figure
          caption="One adapter, both Next routers (App or Pages) — and base-path aware:"
          code={DOCS_VARIANTS}
        />
        <Figure
          captionId="options"
          caption="Every entry point accepts the same options object:"
          code={DOCS_OPTIONS}
        />
        <aside className="note">
          <strong>Caveat:</strong> every frame writes via <code>history.replaceState</code>,
          so back/forward stays untouched — but the browser&apos;s own URL history/autocomplete
          (and any extension listening for <code>webNavigation.onHistoryStateUpdated</code>) can
          still log each frame as a visit. There&apos;s no API to opt a{' '}
          <code>replaceState</code> call out of that; keep <code>duration</code> short,{' '}
          <code>maxFrames</code> low, or use <code>scope: &quot;tail&quot;</code> to cut the frame
          count.
        </aside>
      </article>
    </div>
  );
}
