// demo/angular-router/app.component.ts
import { Component, inject, signal } from '@angular/core';
import { NavigationEnd, Router, RouterOutlet } from '@angular/router';
import { GLYPHNAV } from 'glyphnav/angular-router';
import {
  HEX,
  MATRIX,
  SYMBOLS,
  URL_SAFE,
  type AnimateScope,
  type CommitTiming,
  type GlyphEffect,
} from 'glyphnav/core';
import { GlyphnavLinkDirective } from './glyphnav-link.directive';

const charsets: Record<string, string> = { url: URL_SAFE, hex: HEX, matrix: MATRIX, symbols: SYMBOLS };

function currentUrl(): string {
  return location.pathname + location.search + location.hash;
}

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, GlyphnavLinkDirective],
  template: `
    <h1>
      <a href="/" data-glyphnav="off">glyphnav</a>
      <span class="crumb">&ngsp;/ angular-router</span>
    </h1>

    <p class="bar" [class.resolving]="resolving()">
      Watch the address bar. Current path: <span class="path">{{ path() }}</span>
    </p>

    <nav>
      <a href="/angular-router/" glyphnavLink="/" [class.active]="active() === '/'">home</a>
      <a href="/angular-router/about" glyphnavLink="/about" [class.active]="active() === '/about'">about</a>
      <a href="/angular-router/docs" glyphnavLink="/docs" [class.active]="active() === '/docs'">docs</a>
      <a href="/angular-router/blog" glyphnavLink="/blog" [class.active]="active() === '/blog'">blog</a>
    </nav>

    <p class="deep">
      deep links:
      <a href="/angular-router/about?ref=deep&page=2" glyphnavLink="/about?ref=deep&page=2">?query</a>
      <a href="/angular-router/docs#options" glyphnavLink="/docs#options">#hash</a>
      <a href="/angular-router/about?q=glyph#results" glyphnavLink="/about?q=glyph#results">?query+#hash</a>
    </p>

    <div class="controls">
      <label>charset
        <select (change)="onCharset($event)">
          <option value="url">url-safe</option>
          <option value="hex">hex</option>
          <option value="matrix">matrix</option>
          <option value="symbols">symbols</option>
        </select>
      </label>
      <label>speed
        <input type="range" min="20" max="1000" step="10" [value]="1020 - duration()" (input)="onSpeed($event)" />
        <span class="ms">{{ duration() }}ms</span>
      </label>
      <label>effect
        <select (change)="onEffect($event)">
          <option value="decode">decode</option>
          <option value="scramble">scramble</option>
        </select>
      </label>
      <label>commit
        <select (change)="onCommit($event)">
          <option value="before">navigate first</option>
          <option value="after">animate first</option>
        </select>
      </label>
      <label>scope
        <select (change)="onScope($event)">
          <option value="full">full</option>
          <option value="tail">tail</option>
        </select>
      </label>
    </div>

    <router-outlet></router-outlet>

    <p class="foot">
      The <code>[glyphnavLink]</code> directive is copied from this demo into your app and calls
      the injected navigator. Compiled with Angular JIT inside the shared playground — the title
      link is a plain full-page load back to the picker.
    </p>
  `,
})
export class AppComponent {
  private readonly nav = inject(GLYPHNAV);

  readonly path = signal(currentUrl());
  readonly resolving = signal(false);
  readonly active = signal('/');
  readonly duration = signal(250);

  private charset = URL_SAFE;
  private effect: GlyphEffect = 'decode';
  private commit: CommitTiming = 'before';
  private scope: AnimateScope = 'full';

  constructor() {
    this.apply();
    inject(Router).events.subscribe((event) => {
      if (event instanceof NavigationEnd) {
        this.active.set(event.urlAfterRedirects.split(/[?#]/)[0]);
      }
    });
  }

  private apply(): void {
    this.nav.controller.update({
      charset: this.charset,
      duration: this.duration(),
      effect: this.effect,
      commit: this.commit,
      scope: this.scope,
      hooks: {
        onFrame: (f) => {
          this.path.set(f.path);
          this.resolving.set(f.phase === 'resolve');
        },
        onComplete: () => {
          this.resolving.set(false);
          this.path.set(currentUrl());
        },
      },
    });
  }

  onCharset(event: Event): void {
    this.charset = charsets[(event.target as HTMLSelectElement).value];
    this.apply();
  }

  onSpeed(event: Event): void {
    // Slider is inverted: full right = 20 ms (fastest whole animation).
    this.duration.set(1020 - Number((event.target as HTMLInputElement).value));
    this.apply();
  }

  onEffect(event: Event): void {
    this.effect = (event.target as HTMLSelectElement).value as GlyphEffect;
    this.apply();
  }

  onCommit(event: Event): void {
    this.commit = (event.target as HTMLSelectElement).value as CommitTiming;
    this.apply();
  }

  onScope(event: Event): void {
    this.scope = (event.target as HTMLSelectElement).value as AnimateScope;
    this.apply();
  }
}

// demo/vue-router/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useGlyphnav } from 'glyphnav/vue-router';
import {
  HEX,
  MATRIX,
  SYMBOLS,
  URL_SAFE,
  type AnimateScope,
  type CommitTiming,
  type FrameInfo,
  type GlyphEffect,
} from 'glyphnav/core';

const controller = useGlyphnav();

const currentUrl = () => location.pathname + location.search + location.hash;

const displayPath = ref(currentUrl());
const resolving = ref(false);
const duration = ref(250);

const charsets: Record<string, string> = { url: URL_SAFE, hex: HEX, matrix: MATRIX, symbols: SYMBOLS };
const state = {
  charset: URL_SAFE,
  duration: 250,
  effect: 'decode' as GlyphEffect,
  commit: 'before' as CommitTiming,
  scope: 'full' as AnimateScope,
};

function apply(): void {
  controller.update({
    ...state,
    hooks: {
      onFrame: (f: FrameInfo) => {
        displayPath.value = f.path;
        resolving.value = f.phase === 'resolve';
      },
      onComplete: () => {
        resolving.value = false;
        displayPath.value = currentUrl();
      },
    },
  });
}
apply();

const onCharset = (e: Event) => {
  state.charset = charsets[(e.target as HTMLSelectElement).value];
  apply();
};
const onSpeed = (e: Event) => {
  // Slider is inverted: full right = 20 ms (fastest whole animation).
  state.duration = 1020 - Number((e.target as HTMLInputElement).value);
  duration.value = state.duration;
  apply();
};
const onEffect = (e: Event) => {
  state.effect = (e.target as HTMLSelectElement).value as GlyphEffect;
  apply();
};
const onCommit = (e: Event) => {
  state.commit = (e.target as HTMLSelectElement).value as CommitTiming;
  apply();
};
const onScope = (e: Event) => {
  state.scope = (e.target as HTMLSelectElement).value as AnimateScope;
  apply();
};
</script>

<template>
  <h1><a href="/">glyphnav</a> <span class="crumb">/ vue-router</span></h1>

  <p class="bar" :class="{ resolving }">
    Watch the address bar. Current path: <span class="path">{{ displayPath }}</span>
  </p>

  <nav>
    <router-link to="/">home</router-link>
    <router-link to="/about">about</router-link>
    <router-link to="/features">features</router-link>
    <router-link to="/docs">docs</router-link>
  </nav>

  <p class="deep">
    deep links:
    <router-link to="/about?ref=deep&page=2">?query</router-link>
    <router-link to="/docs#options">#hash</router-link>
    <router-link to="/about?q=glyph#results">?query+#hash</router-link>
  </p>

  <div class="controls">
    <label>charset
      <select @change="onCharset">
        <option value="url">url-safe</option>
        <option value="hex">hex</option>
        <option value="matrix">matrix</option>
        <option value="symbols">symbols</option>
      </select>
    </label>
    <label>speed
      <input type="range" min="20" max="1000" step="10" :value="1020 - duration" @input="onSpeed" />
      <span class="ms">{{ duration }}ms</span>
    </label>
    <label>effect
      <select @change="onEffect">
        <option value="decode">decode</option>
        <option value="scramble">scramble</option>
      </select>
    </label>
    <label>commit
      <select @change="onCommit">
        <option value="before">navigate first</option>
        <option value="after">animate first</option>
      </select>
    </label>
    <label>scope
      <select @change="onScope">
        <option value="full">full</option>
        <option value="tail">tail</option>
      </select>
    </label>
  </div>

  <router-view />

  <p class="foot">
    Every <code>&lt;router-link&gt;</code> goes through the wrapped <code>router.push</code>. The
    title link is a plain anchor, so it leaves the SPA with a normal page load.
  </p>
</template>
